module.exports = handleError = async (ctx)=>{
    await ctx.reply("An error occured, please try again.")
}